# Generated by Django 2.0.6 on 2018-06-19 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creattime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 8, 16, 51, 956409)),
        ),
        migrations.AddField(
            model_name='product',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 19, 8, 16, 51, 956436)),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgpath',
            field=models.ImageField(upload_to='images'),
        ),
    ]
