# Generated by Django 2.0.6 on 2018-06-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180619_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commentamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='salesamount',
            field=models.IntegerField(default=0),
        ),
    ]
