# Generated by Django 2.0.6 on 2018-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180619_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='producttab',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('skuid', models.IntegerField(default=0)),
                ('tabname', models.CharField(max_length=50)),
            ],
        ),
    ]
