# Generated by Django 2.0.6 on 2018-06-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='productstar',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('skuid', models.IntegerField()),
            ],
        ),
    ]
