# Generated by Django 2.0.6 on 2018-07-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180705_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='skuid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
