# Generated by Django 2.0.6 on 2018-07-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_comment_stars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
