# Generated by Django 2.0.6 on 2018-07-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('skuid', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
