# Generated by Django 2.0.6 on 2018-07-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userid',
        ),
    ]
