# Generated by Django 2.0.6 on 2018-07-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_userstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productstar',
        ),
    ]
