# Generated by Django 2.0.6 on 2018-07-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_shopcar_updatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcar',
            name='product',
        ),
        migrations.AddField(
            model_name='shopcar',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
