# Generated by Django 2.0.6 on 2018-07-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20180712_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='addnum',
            field=models.IntegerField(default=1),
        ),
    ]
