# Generated by Django 2.0.6 on 2018-08-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_shopcar_addnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='ischose',
            field=models.IntegerField(default=0),
        ),
    ]
