# Generated by Django 2.0.6 on 2018-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_shopcar_ischose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterField(
            model_name='product',
            name='commentamount',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creattime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(max_length=200, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext1',
            field=models.CharField(default='', max_length=200, verbose_name='额外字段1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext2',
            field=models.CharField(default='', max_length=200, verbose_name='额外字段2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext3',
            field=models.CharField(default='', max_length=200, verbose_name='额外字段3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgpath',
            field=models.ImageField(upload_to='images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producttype',
            field=models.CharField(default='', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salesamount',
            field=models.IntegerField(default=0, verbose_name='售出数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
