# Generated by Django 2.0.6 on 2018-07-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
