# Generated by Django 2.0.6 on 2018-08-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auth_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_profile',
            name='phonenum',
            field=models.CharField(default='', max_length=20),
        ),
    ]
