# Generated by Django 2.0.6 on 2018-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_auth_profile_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerlist',
            name='imgpath',
            field=models.ImageField(upload_to='images', verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='bannerlist',
            name='name',
            field=models.CharField(max_length=20, verbose_name='广告名字'),
        ),
    ]
