# Generated by Django 2.0.6 on 2018-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20180815_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerlist',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='bannerlist',
            name='imgurl',
            field=models.ImageField(default='', upload_to='images', verbose_name='图片链接'),
        ),
    ]
