# Generated by Django 2.0.6 on 2018-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20180815_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerlist',
            name='imagepath',
            field=models.CharField(default='', max_length=200),
        ),
    ]
