# Generated by Django 2.0.6 on 2018-08-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_bannerlist_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerlist',
            name='imgurl',
        ),
        migrations.AlterField(
            model_name='bannerlist',
            name='imagepath',
            field=models.ImageField(default='', upload_to='images', verbose_name='图片链接'),
        ),
    ]
