# Generated by Django 2.0.6 on 2018-08-15 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_auto_20180815_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth_profile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='bannerlist',
            options={'verbose_name': '广告列表', 'verbose_name_plural': '广告列表'},
        ),
        migrations.AlterField(
            model_name='auth_profile',
            name='phonenum',
            field=models.CharField(default='', max_length=20, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='auth_profile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='auth_profile',
            name='userimg',
            field=models.ImageField(upload_to='images', verbose_name='用户头像'),
        ),
    ]
